### ISSUE TITLE
Decouple the scheduling system from eNMS

### ISSUE THREAD

**Issue by shorton3** [eNMS-automation/eNMS#129]
The scheduling system should be a different, but highly monitored Flask application with a REST API to schedule jobs, and eNMS workers would communicate with that application. This solves the problem of scaling eNMS to multiple instances (since the scheduler is difficult to make redundant), and not only to multiple processes within the same instance (since starting eNMS with multiple gunicorn workers causes APScheduler to be duplicated in each worker, thus having to scale back to a single worker).

Thank you!

**Comment by afourmy** [comment]
Done
