### ISSUE TITLE
Add batch selection 、editing 、delete functions in inventory & automation tables 

### ISSUE THREAD

**Issue by victor051** [eNMS-automation/eNMS#133]
Currently, after adding a few devices to the inventory, When you delete or edit a device, you need to click and modify it multiple times. It is recommended to add a check box to batch edit or delete.

**Comment by afourmy** [comment]
Batch editing can already by done for the inventory with Excel:
- export your network from the "Inventory / Import & Export" page
- modify it with Excel
- import it

**Comment by victor051** [comment]
Yes, we can do this, but it is not as easy to operate as the checkbox. I believe this will make the user feel easier to use.
Also，there is no bulk delete in Service Management,maybe consider adding the option to "disable".

**Comment by afourmy** [comment]
all of that is now supported in the latest version
