### ISSUE TITLE
Adding support for use_genie in Netmiko services

### ISSUE THREAD

**Issue by Tarik-H** [eNMS-automation/eNMS#159]
Hello,
Is it possible to add support for "use_genie=True" argument in Netmiko send_command() within Netmiko services please?
The advantage of using genie instead of TextFSM is the fact that it comes out of the box with over 800 ready parsers without the need to create templates.
It would require adding pyats and genie into requirements.txt and a checkbox into Netmiko services forms to activate the argument similar to fast_cli.

**Comment by shorton3** [comment]
Hi Tarik, looking at your suggestion. Is this the project that you're recommending: https://github.com/CiscoTestAutomation/genieparser ?
Is my understanding correct that this would take the raw output from the device (and from Netmiko) and parse the unstructured data into a json/dictionary structure?  If so, would the user be required to specify which parser to use? And if so, is there an index of parsers for each device type that can be read in?  I'm interested to know more...

**Comment by Tarik-H** [comment]
Hi Stephen,
I think the link you provided is for a parser library inside the [Genie suite of libraries](https://developer.cisco.com/docs/genie-docs/). It comes with already built-in parsers listed here: https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/parsers .
Netmiko added the support of genie as an argument to [send_command](https://ktbyers.github.io/netmiko/docs/netmiko/index.html#netmiko.BaseConnection.send_command) , if it's enabled and the command you're sending is supported by the out-of-the box genie parsers  (ex: show interfaces) it will return the structured output.

**Comment by mww012** [comment]
Hey guys,
I'm taking a swing at adding the Genie functionality.  So far I've got it working with the netmiko validation service.  When Genie successfully parses a response it hands back a dict.  If it doesn't parse successfully it just gives back the raw text like normal service output.  I've added a screenshot to show the eNMS results page.  The "show interface" command I ran got parsed by Genie and is broken down by port.

@Tarik-H is this what you were looking for?  The dict is also available in the post-processing field.

<img width="1663" alt="Screen Shot 2020-01-28 at 12 08 37 AM" src="https://user-images.githubusercontent.com/4991000/73239804-cff8a200-4162-11ea-9bc2-556241e2cc75.png">

**Comment by tkspuk** [comment]
@mww012 Could you share more details，the Genie just support cisco device？

**Comment by afourmy** [comment]
@tkspuk Yes it is only for Cisco, but given that it is an option in netmiko, it makes sense to support it in eNMS too.
@mww012 I think this is exactly what we're looking for. Get it to work with the netmiko validation service is all we need, I don't think it makes sense to support it in other services. You're welcome to open a PR if it is working. Thanks !

**Comment by mww012** [comment]
It's primarily Cisco.  There are a few Juniper and Linux commands that can be successfully parsed.
I honestly don't have a lot of experience with Genie so @Tarik-H may be able to speak to its full scope.

Here are the parsers in Genie.
[](https://github.com/CiscoTestAutomation/genieparser/tree/master/src/genie/libs/parser)

**Comment by tkspuk** [comment]
@mww012 @afourmy  I understand, add parameters when sending commands，
It's can add testfsm templates or other, but you need to write your own templates when use the testfsm
def send_command(use_textfsm=False, textfsm_template=None, use_genie=False)

**Comment by mww012** [comment]
Yes.  That's my understanding.  It can be used similarly to TextFSM but comes with a lot a pre-built parsers.

**Comment by mww012** [comment]
I'd like to do a little more testing and I'll try to get the PR put in this evening.
