### ISSUE TITLE
Cant get eNMS to import from Netbox

### ISSUE THREAD

**Issue by Geertkok1** [eNMS-automation/eNMS#171]
eNMS version: 3.18.2
I am trying to get eNMS to import the topology from Netbox. For this I have set the netbox host in the config.json file and executed the following command:
`export NETBOX_TOKEN=MyNetboxToken`
When I press the "import from netbox button" on the admin page of eNMS nothing is imported. In the log file I can see that eNMS starts a request to netbox but a 403 error is returned. When I run a self-made python script with the same request and same API key I successfully get a list of device back.
Is there any further configuration needed for Netbox import to work?

**Comment by tkspuk** [comment]
@Geertkok1 What is the final result? solved? If you need help with netbox import, you can contact me

**Comment by Geertkok1** [comment]
@tkspuk Yes we solved the problem ourselves. Thank you for offering the help
