### ISSUE TITLE
Downloading files from "Files" menu fails

### ISSUE THREAD

**Issue by mww012** [eNMS-automation/eNMS#191]
On 3.20.0 downloading a file from the Files menu fails due to an extra slash in the URL (see screenshot).
![Screen Shot 2020-02-13 at 4 45 42 PM](https://user-images.githubusercontent.com/4991000/74485757-14817e80-4e81-11ea-93e8-829d7ffe01bb.png)

**Comment by afourmy** [comment]
RBAC bug, should be fixed in the version I just pushed.
