### ISSUE TITLE
Don't work button "Automation->Services->Parameterized run" since v3.19

### ISSUE THREAD

**Issue by Fikirsiz** [eNMS-automation/eNMS#192]
When I click on the button, nothing happens.
![Screenshot from 2020-02-14 12-25-36](https://user-images.githubusercontent.com/20380238/74518618-36ccd800-4f25-11ea-8aa4-a94c17a72657.png)
I also noticed that the REST API /rest/run_service does not work either. I think these are related problems.

**Comment by afourmy** [comment]
The parameterized bug is fixed, it was a front-end issue so it isn't related to anything else. The run_service endpoint in the REST API works fine as far as I can tell
