### ISSUE TITLE
How to add another dropdown  like BGP form

### ISSUE THREAD

**Issue by bibin0dilli** [eNMS-automation/eNMS#199]
I want to create a form like similar to BGP for access port configuration .Please let me know the way on how to add a drop down similar to the BGP form.

**Comment by afourmy** [comment]
by reusing code from the example service

**Comment by bibin0dilli** [comment]
![Capture111](https://user-images.githubusercontent.com/58481777/75104032-af205100-5629-11ea-82ff-1fef0c9278f5.JPG)


I get the following error .Created a new program in the sam efolder
