### ISSUE TITLE
eNMS craches with error: "Can't reconnect until invalid transaction is rolled back"

### ISSUE THREAD

**Issue by Fikirsiz** [eNMS-automation/eNMS#201]
eNMS crashes with the following error:

[traceback.txt](https://github.com/eNMS-automation/eNMS/files/4248814/traceback.txt)

**Comment by afourmy** [comment]
how to reproduce it ? with that much information there is nothing I can do

**Comment by Fikirsiz** [comment]
Sorry, I caught this error two times but didn't realize how to reproduce it. Next time I will provide more information.

**Comment by afourmy** [comment]
not actionable (the traceback doesn't tell us anything), you can reopen or create a new issue when you have more info
