### ISSUE TITLE
Urgent - Issue with cisco_wlc_ssh

### ISSUE THREAD

**Issue by bibin0dilli** [eNMS-automation/eNMS#214]
The controller logins always give error , changing timeout to 10 does not  help either .any help will be appreciated.

Below is the Error
#################
Traceback (most recent call last):
 File \"c:\\users\\bbahuley\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\paramiko\\transport.py\", line 2211, in _check_banner
   buf = self.packetizer.readline(timeout)
 File \"c:\\users\\bbahuley\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\paramiko\\packet.py\", line 380, in readline
   buf += self._read_timeout(timeout)
 File \"c:\\users\\bbahuley\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\paramiko\\packet.py\", line 622, in _read_timeout
   raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File \"C:\\Users\\bbahuley\\Videos\\eNMS-master\\eNMS-master\\eNMS\\models\\automation.py\", line 547, in run_service_job
   results = self.service.job(self, payload, *args)
 File \"C:\\Users\\bbahuley\\Videos\\eNMS-master\\eNMS-master\\eNMS\\services\\data_validation\
etmiko_validation.py\", line 35, in job
   netmiko_connection = run.netmiko_connection(device)
 File \"C:\\Users\\bbahuley\\Videos\\eNMS-master\\eNMS-master\\eNMS\\models\\automation.py\", line 938, in netmiko_connection
   session_log=BytesIO(),
 File \"c:\\users\\bbahuley\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\
etmiko\\ssh_dispatcher.py\", line 246, in ConnectHandler
   return ConnectionClass(*args, **kwargs)
 File \"c:\\users\\bbahuley\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\
etmiko\\base_connection.py\", line 317, in __init__
   self._open()
 File \"c:\\users\\bbahuley\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\
etmiko\\base_connection.py\", line 322, in _open
   self.establish_connection()
 File \"c:\\users\\bbahuley\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\
etmiko\\base_connection.py\", line 884, in establish_connection
   self.remote_conn_pre.connect(**ssh_connect_params)
 File \"c:\\users\\bbahuley\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\paramiko\\client.py\", line 406, in connect
   t.start_client(timeout=timeout)
 File \"c:\\users\\bbahuley\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\paramiko\\transport.py\", line 660, in start_client
   raise e
 File \"c:\\users\\bbahuley\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\paramiko\\transport.py\", line 2039, in run
   self._check_banner()
 File \"c:\\users\\bbahuley\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\paramiko\\transport.py\", line 2216, in _check_banner
   \"Error reading SSH protocol banner\" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

**Comment by afourmy** [comment]
this is a netmiko stacktrace, unrelated to enms
