### ISSUE TITLE
Error: Can't reconnect until invalid transaction is rolled back

### ISSUE THREAD

**Issue by Fikirsiz** [eNMS-automation/eNMS#218]
My traceback: [traceback.txt](https://github.com/eNMS-automation/eNMS/files/4473109/traceback.txt)
I investigated this error and tried all supported databases. The connection to the database has never fallen. I noticed that an error occurs when my server is inactive for a long time. The last time I got an error after I did not log in to eNMS for 13 hours.
I think that the problem is related to the database settings: wait_timeout and interactive_timeout, whose default value is 8 hours. I think that the session between the database and eNMS closes by timeout.

**Comment by afourmy** [comment]
I've seen that before, you can increase the wait_timeout parameter (mysql conf), for example `wait_timeout=31536000` (there is a `pool_pre_ping` sqlalchemy parameter that I think should be responsible for dealing with that, but in practice it doesn't seem to help)
I'll leave this issue open, maybe we'll fix it properly in the code at some point

**Comment by afourmy** [comment]
hasn't heard about this in a year, it never happens if the database is properly configured => closing
