### ISSUE TITLE
Ansible Play Book Run error

### ISSUE THREAD

**Issue by bibin0dilli** [eNMS-automation/eNMS#219]
File \"/usr/lib/python3.6/subprocess.py\", line 438, in run
   output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ansible-playbook', '-i', '10.99.99.12,', '/root/Virtual/eNMS/files/playbooks/simple_playbook.yml']' returned non-zero exit status 1.

I get this error on any playbook i run.

Please fix

**Comment by afourmy** [comment]
regression tests are not meant to be run by users
