### ISSUE TITLE
Delete a Workflow does not work .

### ISSUE THREAD

**Issue by bibin0dilli** [eNMS-automation/eNMS#221]
![image](https://user-images.githubusercontent.com/58481777/79417963-124ab600-7fd1-11ea-8e02-322c2f3016e7.png)

When we try to delete a work flow , it does not work.

**Comment by afourmy** [comment]
The delete button is meant to delete services, edges and labels inside a workflow, not the workflow itself (that cannot be done from the workflow builder, only from the service management page)
