### ISSUE TITLE
How to import bulk devices

### ISSUE THREAD

**Issue by bibin0dilli** [eNMS-automation/eNMS#222]
Hi,

 I do not see the import option in inventory in this version .I want to bulk add 5000 devices .Is there any way to do it .

**Comment by bibin0dilli** [comment]
I found it  it in "Admin".I trid to upload an excel but did not reflect.Is there any format to upload.

**Comment by flunka** [comment]
@bibin0dilli Have you tried excel format like [this](https://github.com/eNMS-automation/eNMS/blob/master/files/spreadsheets/usa.xls)? In [files/spreadsheets](https://github.com/eNMS-automation/eNMS/tree/master/files/spreadsheets) you can find some examples.
