### ISSUE TITLE
Comparing V1 and V2 of 2 devices , Throws an error always

### ISSUE THREAD

**Issue by bibin0dilli** [eNMS-automation/eNMS#223]
![image](https://user-images.githubusercontent.com/58481777/79668210-daf82700-81d3-11ea-93aa-3b5a47efea8b.png)
Even though V1 and V2 are selected , it keeps on throwing error to select 2 verison.
Possibble Bug?

**Comment by bibin0dilli** [comment]
@afourmy

**Comment by afourmy** [comment]
This is fixed in the latest release
