### ISSUE TITLE
Site doesnt respond to clicks after launching it 

### ISSUE THREAD

**Issue by hett39** [eNMS-automation/eNMS#225]
I installed ENMS on windows 10 with Py 3.7. After I ran the flask run command I was able to open the link and login with admin but then I cannot click any tab or icons on site.

![enms](https://user-images.githubusercontent.com/30513200/79928674-68b45c00-83f8-11ea-97cb-42c725b633ce.JPG)

**Comment by afourmy** [comment]
windows is not supported

**Comment by hett39** [comment]
Ok. Is it in roadmap to add windows support  ?
