### ISSUE TITLE
TACACS/LDAP Authentication NOT working

### ISSUE THREAD

**Issue by bibin0dilli** [eNMS-automation/eNMS#237]
I have Configured TACACS SERVER and KEY in the SERVER BUT IT DENIES ACCES.PLEASE HELP.

ALSO LDAP DOSENT WORK TOO

2020-05-11 18:04:38,423 INFO     Authentication failed ('App' object has no attribute 'tacacs_client')
2020-05-11 18:04:38,428 INFO     10.213.80.219 - - [11/May/2020 18:04:38] "POST /login HTTP/1.1" 403 -

**Comment by bibin0dilli** [comment]
@afourmy Any help

**Comment by bibin0dilli** [comment]
2020-05-13 20:16:32,970 DEBUG    TACACSAuthenticationStart
sent header <version: 192, type: 1, session_id: 616727754, length: 40, seq_no: 1, flags: 0>
sent body <action: 1, authen_type: 1, authen_service: 1, data: b'', data_len: 0, priv_lvl: 0, port: python_tty0, port_len: 11, rem_addr: python_device, rem_addr_len: 13, user: bbahuley, user_len: 8>
2020-05-13 20:16:33,163 ERROR    Authentication failed (Unable to extract data from header. Likely the TACACS+ key does not match between server and client)




Where should i configure the Tacacs+ key , is it picking the key from Secret_key ? 
@afourmy

**Comment by MiShRob** [comment]
@bibin0dilli  I assume you're talking about the tacacs that the controller uses. 

The tacacs password is set in an environment variable.

https://github.com/eNMS-automation/eNMS/blob/cedfde241ce8336b9d64171c715ee480d8f149fd/eNMS/controller/base.py#L251-L254

**Comment by bibin0dilli** [comment]
@MiShRob i want to login to eNMS using TACACS+ , the server is hosted in my enterprise, To authenticate , i need a key to be used in the eNMS tool, i need to understand where should i give that key .

Attached image below

![image](https://user-images.githubusercontent.com/58481777/81896780-f0921e00-95d2-11ea-9793-86259b87d6b2.png)

**Comment by jpobeda** [comment]
@bibin0dilli If you read @MiShRob comment carefully, you'll see the answer. It expects you to have an environment variable set with the TACACS_PASSWORD

` self.settings["tacacs"]["address"], 49, environ.get("TACACS_PASSWORD") `

**Comment by prasathn1984** [comment]
I am also facing same problems. i unable to look tacacs settings in basy.py. could anyone let me know the steps to configure tacacs settings?
