### ISSUE TITLE
The service can't run after I click the run button sometimes.

### ISSUE THREAD

**Issue by yangjingcaroline** [eNMS-automation/eNMS#249]
The service can't run after I click the run button sometimes.
![1590390849114](https://user-images.githubusercontent.com/47808579/82788129-70a16900-9e9a-11ea-8196-861711af9c05.jpg)

**Comment by afourmy** [comment]
usually this is because the service is in "run once per device mode", but there are no devices configured as targets so nothing happens because there isn't anything to do, can you check ?

**Comment by yangjingcaroline** [comment]
> usually this is because the service is in "run once per device mode", but there are no devices configured as targets so nothing happens because there isn't anything to do, can you check ?

I just checked and a device was attached to this service when I created the service.
![1590393549660](https://user-images.githubusercontent.com/47808579/82791659-be20d480-9ea0-11ea-9e46-e8a343a092a1.jpg)

**Comment by yangjingcaroline** [comment]
I tried to change the code like this to solving the problem, because when I called the log function in the file to see the logs it failed.
![image](https://user-images.githubusercontent.com/47808579/83091667-420bd400-a0ce-11ea-9646-61bc0f3e76dc.png)

**Comment by afourmy** [comment]
@yangjingcaroline Does that fix the problem you reported ? I think I fixed it too in the master branch, as you can see here: https://github.com/eNMS-automation/eNMS/blob/master/eNMS/models/automation.py#L814
but is that related to your original issue ?

**Comment by yangjingcaroline** [comment]
> @yangjingcaroline Does that fix the problem you reported ? I think I fixed it too in the master branch, as you can see here: https://github.com/eNMS-automation/eNMS/blob/master/eNMS/models/automation.py#L814
> but is that related to your original issue ?

No. My solution does not work. I will try your solution later. Thanks very much for your reply.

**Comment by yangjingcaroline** [comment]
resolved.
