### ISSUE TITLE
when I changed my user password, it reported a type error.

### ISSUE THREAD

**Issue by yangjingcaroline** [eNMS-automation/eNMS#252]
I found when I changed my user password, it would report an error like this below. By the way, the vault service is active.
![1](https://user-images.githubusercontent.com/47808579/83619665-c672c100-a5be-11ea-9456-599a59e88647.png)
But if I modified the code like this below, the problem resolved.
![2](https://user-images.githubusercontent.com/47808579/83619914-1b163c00-a5bf-11ea-8f36-b828ac0ab906.jpg)

**Comment by afourmy** [comment]
I think the problem is that your Vault does not accept bytes because it is an old version. Can you upgrade your vault to the latest version available and see if it works without your change ?

**Comment by yangjingcaroline** [comment]
> I think the problem is that your Vault does not accept bytes because it is an old version. Can you upgrade your vault to the latest version available and see if it works without your change ?

I works for me. Thanks very much.
