### ISSUE TITLE
some tacacs user can't see some object list such as device, service or pool.

### ISSUE THREAD

**Issue by yangjingcaroline** [eNMS-automation/eNMS#253]
I crated a self designed group called netops-member. The inventory menu and the devices page were all selected. 
![4](https://user-images.githubusercontent.com/47808579/83851475-ffd53900-a744-11ea-8978-7ca6113e2fef.jpg)
![6](https://user-images.githubusercontent.com/47808579/83851809-770acd00-a745-11ea-9670-74a13dbbec79.jpg)

But when I logged in eNMS by the user which was in the group, I couldn't see the device list.
![7](https://user-images.githubusercontent.com/47808579/83851985-b507f100-a745-11ea-9a8a-9b1545a2b50d.jpg)

**Comment by afourmy** [comment]
When you tested it, the implementation wasn't finished yet. Now it has evolved a lot, and RBAC is now configured with a special type of object called `access` in the "Access" menu. The RBAC mechanism in your screenshot no longer exists so I'll close this.
