### ISSUE TITLE
Feature Request: Add sshkey based auth to devices

### ISSUE THREAD

**Issue by dBitech** [eNMS-automation/eNMS#255]
I have a large number of devices in my management tree which can only accept key-based authentication. I didn't see an already existing Feature Request for this so here it is.

**Comment by dBitech** [comment]
Some thoughts:

Under the Administration panel, have a Key management Section, which will allow you to add/modify/delete keys. you associate a name with the key. (by default it reads this out of the key), which you can override. 

In the device administration section, where you can specify the username/password, you have a checkbox to "Use key" with a select box of all of the named keys.   This same Username/Password/Key is used throughout the various places where a username/password can be chosen for device management.

**Comment by afourmy** [comment]
sshkey based auth implemented in latest version
