### ISSUE TITLE
New Installation Fails - GitHub Authentication

### ISSUE THREAD

**Issue by MattCrum1** [eNMS-automation/eNMS#256]
I'm trying to install eNMS on Centos7 and followed the instructions from the GitHub page here: 

https://github.com/eNMS-automation/eNMS

During the first run, it installed loads of files - but failed at the following step:

> 2020-06-08 13:11:29,150 DEBUG    Popen(['git', 'clone', '-v', 'git@github.com:afourmy/gitpython-test.git', '/opt/enms/eNMS/network_data'], cwd=/opt/enms/eNMS, universal_newlines=True, shell=None, istream=None)
> The authenticity of host 'github.com (140.82.114.4)' can't be established.
> RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
> RSA key fingerprint is MD5:16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
> Are you sure you want to continue connecting (yes/no)? yes
> 2020-06-08 13:11:34,488 DEBUG    Cmd(['git', 'clone', '-v', 'git@github.com:afourmy/gitpython-test.git', '/opt/enms/eNMS/network_data'])'s unused stdout: Cloning into '/opt/enms/eNMS/network_data'...
> 
> 2020-06-08 13:11:34,489 DEBUG    AutoInterrupt wait stderr: b"Warning: Permanently added 'github.com,140.82.114.4' (RSA) to the list of known hosts.\nPermission denied (publickey).\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
> 2020-06-08 13:11:34,489 ERROR    Git pull failed (Cmd('git') failed due to: exit code(128)
>   cmdline: git clone -v git@github.com:afourmy/gitpython-test.git /opt/enms/eNMS/network_data
>   stderr: 'Warning: Permanently added 'github.com,140.82.114.4' (RSA) to the list of known hosts.
> Permission denied (publickey).

I tried rerunning flask, but it constantly complains that the Address is already in use, after trying to load Plugin 1:

```
2020-06-08 13:27:37,909 INFO     Loading plugin: Plugin 1
OSError: [Errno 98] Address already in use
```

I checked and Port 80 is not listening elsewhere, so I'm not sure what it is complaining about - any idea what could be happening or how to fix the installation?

**Comment by afourmy** [comment]
if it says the address is in use then the application should be running. By default on port 5000 I think, it won't listen to port 80 unless you configure nginx to do so

**Comment by MattCrum1** [comment]
Hi Antoine,

Thanks for the reply - I've made it run on a different port to avoid the "Address already in use" issue (flask run --host=0.0.0.0 --port=8005) and now it gets further, but still fails at the github bit - can we check that "gitpython-test.git" exists? I've had a look and can't see it (perhaps it needs to be made public so we don't need to log in to github)?

This is the error that I'm seeing:

```
2020-06-09 04:52:59,076 DEBUG    Popen(['git', 'clone', '-v', 'git@github.com:afourmy/gitpython-test.git', '/opt/enms/eNMS/network_data'], cwd=/opt/enms/eNMS, universal_newlines=True, shell=None, istream=None)
2020-06-09 04:52:59,259 DEBUG    Cmd(['git', 'clone', '-v', 'git@github.com:afourmy/gitpython-test.git', '/opt/enms/eNMS/network_data'])'s unused stdout: Cloning into '/opt/enms/eNMS/network_data'...

2020-06-09 04:52:59,259 DEBUG    AutoInterrupt wait stderr: b"Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.\nPermission denied (publickey).\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
2020-06-09 04:52:59,259 ERROR    Git pull failed (Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v git@github.com:afourmy/gitpython-test.git /opt/enms/eNMS/network_data
  stderr: 'Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
Permission denied (publickey).
```

**Comment by afourmy** [comment]
it's called "Topology import", see https://enms.readthedocs.io/en/latest/inventory/network_creation.html#querying-an-external-api

There is no "integration" with librenms, just a way to import the topology from librenms in a programmatic way, nothing more. It hasn't been tested in a long time so I don't know if this still works.

The git error is caused by the repository configured in the settings here: https://github.com/eNMS-automation/eNMS/blob/master/setup/settings.json#L7, it is meant to be replaced with your own git repository (used for storing configurations etc). It shouldn't prevent the app from loading.
