### ISSUE TITLE
Custom Credential or User credential in"NEtmiko Validation" fails !!!!

### ISSUE THREAD

**Issue by bibin0dilli** [eNMS-automation/eNMS#257]
@afourmy the custom username and password or the user credentials in the Netmiko Validation tab always fails .Is this a bug.It says Authentication fail..

**Comment by afourmy** [comment]
Just tested, both custom and user credentials works fine (they always have). For user credentials, you can only use that option if the user passwords are not hashed, which they are by default (see settings.json) for security purposes
