### ISSUE TITLE
eNMS configuration

### ISSUE THREAD

**Issue by maidoe** [eNMS-automation/eNMS#264]
hello, I am really interested in "" eNMS but I am not a developer and I find that the configuration of eNMS is tedious.

It's been 3 days that I search on the internet how to configure eNMS correctly so that I no longer have the message: WARNING: This is a development server. Do not use it in a production deployment.
and be able to use it properly.

I read the document but I find that it is intended for beginners.

i need help just to get started

**Comment by afourmy** [comment]
This warning isn't raised by eNMS but by Flask. Check out Flask docs for more info
If you deploy eNMS with gunicorn you shouldn't get that warning cf https://enms.readthedocs.io/en/latest/base/installation.html#first-steps
