### ISSUE TITLE
How to wipe data?

### ISSUE THREAD

**Issue by Dees7** [eNMS-automation/eNMS#281]
Hello.
I tried eNMS and install in in venv:
```
python -m venv eNMS
cd eNMS
. ./bin/activate
git clone https://github.com/afourmy/eNMS.git
cd eNMS
pip install -r build/requirements/requirements.txt
export FLASK_APP=app.py
flask run --host=0.0.0.0
```

Now I'd like to start from very begin and delete all (include venv eNMS).
After I do the same I see all my old data (events etc).
Where it stored? how to delete all?

**Comment by afourmy** [comment]
by default if you don't configure any database it uses a SQLite database, so it is store in the `database.db` file
