### ISSUE TITLE
Jump parameters don't save on netmiko backup service

### ISSUE THREAD

**Issue by slashdoom** [eNMS-automation/eNMS#283]
If I create a new netmiko backup service, fill in basic info, enable and fill in the jump on parameters, save it, then re-open the service everything is saved expect for the Jump on info.

It seems to work OK on other netmiko services.

**Comment by afourmy** [comment]
should be fixed in master branch

**Comment by slashdoom** [comment]
Thanks again!

**Comment by haithammog** [comment]
Hello,

The issue still present.
