### ISSUE TITLE
name 'netbox_api' is not defined Error when import topology from Netbox

### ISSUE THREAD

**Issue by htwalid** [eNMS-automation/eNMS#289]
When we tried to import topology from Netbox, bellow the result code :
{
  "duration": "0:00:00",
  "properties": {
    "run": {},
    "service": {
      "completion_time": 1,
      "content_match": "",
      "content_match_regex": false,
      "conversion_method": "none",
      "creator": "admin",
      "definition": "Definition",
      "delete_spaces_before_matching": false,
      "description": "",
      "device_query": "",
      "device_query_property": "ip_address",
      "dict_match": {},
      "display_only_failed_nodes": false,
      "id": 106,
      "impacting": true,
      "import_type": "netbox",
      "include_device_results": false,
      "include_link_in_summary": false,
      "initial_payload": {},
      "iteration_devices": "",
      "iteration_devices_property": "name",
      "iteration_values": "",
      "iteration_variable_name": "iteration_value",
      "last_modified": "2020-09-16 08:17:37.052190",
      "librenms_address": "http://librenms.example.com",
      "log_level": 1,
      "mail_recipient": "",
      "max_number_of_retries": 100,
      "max_processes": 15,
      "maximum_runs": 1,
      "multiprocessing": false,
      "name": "[Regression Workflow N: Topology Import (netbox, librenms, opennms)] Netbox Import",
      "negative_logic": false,
      "netbox_address": "http://127.0.0.1:8080",
      "notification_header": "",
      "number_of_retries": 0,
      "opennms_address": "https://demo.opennms.org/opennms/rest",
      "opennms_devices": "https://demo.opennms.org/opennms/rest/nodes",
      "opennms_login": "demo",
      "operating_system": "",
      "postprocessing": "",
      "postprocessing_mode": "always",
      "preprocessing": "",
      "public": false,
      "reply_to": "",
      "reserved": false,
      "run_method": "once",
      "scoped_name": "Netbox Import",
      "send_notification": false,
      "send_notification_method": "mail",
      "shared": false,
      "skip": false,
      "skip_query": "",
      "skip_value": "True",
      "status": "Idle",
      "time_between_retries": 10,
      "type": "topology_import_service",
      "update_pools": false,
      "validation_condition": "success",
      "validation_method": "none",
      "vendor": "",
      "waiting_time": 0
    }
  },
  "result": "Traceback (most recent call last):\n  File \"/home/vagrant/eNMS/eNMS/models/automation.py\", line 762, in run_service_job\n    results = self.service.job(self, payload, *args)\n  File \"/home/vagrant/eNMS/eNMS/services/miscellaneous/topology_import.py\", line 36, in job\n    getattr(self, f\"query_{self.import_type}\")()\n  File \"/home/vagrant/eNMS/eNMS/services/miscellaneous/topology_import.py\", line 40, in query_netbox\n    nb = netbox_api(self.netbox_address, app.get_password(self.netbox_token))\nNameError: name 'netbox_api' is not defined",
  "runtime": "2020-09-16 08:26:33.112052",
  "state": {
    "106": {
      "status": "Running",
      "success": false
    },
    "status": "Completed"
  },
  "success": false,
  "summary": {
    "failure": [],
    "success": []
  },
  "trigger": "UI"
}

**Comment by afourmy** [comment]
if netbox_api is not defined it probably means the import failed, which means pynetbox is not installed. you can reopen if that wasn't the issue

**Comment by htwalid** [comment]
thanks a lot :+1:  , the issue was solved after installing pynetbox.
