### ISSUE TITLE
Issue when running a Netmiko backup service

### ISSUE THREAD

**Issue by dd1245** [eNMS-automation/eNMS#300]
When running a Netmiko backup service, the following error shows as the result. 

__init__() got an unexpected keyword argument 'global_cmd_verify'

This is one the lastest eNMS version.

**Comment by afourmy** [comment]
`global_cmd_verify` is an argument of netmiko `BaseConnection` `__init__` method, it shouldn't fail unless you're using an old version of netmiko, or a custom netmiko driver that didn't implement it... Is that the case ?

**Comment by dd1245** [comment]
I'm not using a custom driver but will check the version now. It was a fresh install with pip3 on Ubuntu 20.04 so I would have expected it to be fairly current.

I'll check and confirm.

**Comment by dd1245** [comment]
Sorry, it appears it was the version. Please close. 

Apologies for wasting your time.
