### ISSUE TITLE
pool.admin_only does not exist

### ISSUE THREAD

**Issue by dd1245** [eNMS-automation/eNMS#306]
Since the latest update eNMS starts up but I quickly get this issue. I guess its because I don't have this pool in my database?

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column pool.admin_only does not exist
LINE 1: ...reator, pool.access_groups AS pool_access_groups, pool.admin...

**Comment by afourmy** [comment]
- you don't have the admin_only column for pools. Whenever there is a change in the db schema, the db must be migrated
- latest official release is https://github.com/eNMS-automation/eNMS/releases/tag/v3.22.3
- pgsql is not officially supported only mysql and sqlite
