### ISSUE TITLE
SSL Certs

### ISSUE THREAD

**Issue by jarora11** [eNMS-automation/eNMS#308]
Hi,

I was going through the documentation to figure out how/where to load SSL certs for the WEBUI but couldn't find any details on doing this. Does it follow the standard flask processes for deploying SSL certs for the web app?

Thanks

**Comment by LensHunnel** [comment]
Hi, I think that you can, it's a flask app. But you can have it behind a reverse proxy as NGINX and deploy the SSL certs in NGINX : https://nginx.org/en/docs/http/configuring_https_servers.html

**Comment by afourmy** [comment]
ssl certs are configured via nginx etc not eNMS.
