### ISSUE TITLE
 name 'initial_payload' is not defined

### ISSUE THREAD

**Issue by LensHunnel** [eNMS-automation/eNMS#309]
Hi,

I didn't found anything in the doc, I'm trying to use 'initial_payload' parameters in a python  snippet service.
My error in logs was: 
Execution error(line 151): name 'initial_payload' is not defined

But in the doc, it's written that Initial Payload User-defined dictionary that can be used anywhere in the service.

can you enlighten me a little more please? thanks

**Comment by afourmy** [comment]
`payload` should be defined, the initial payload field defines its initial value
