### ISSUE TITLE
Question: Netmiko configuration service

### ISSUE THREAD

**Issue by LensHunnel** [eNMS-automation/eNMS#310]
Hi,

It is possible to use the result of a service in a workflow to populate the content parameter of Netmiko configuration service ? 

Thanks a lot for what your doing !

**Comment by afourmy** [comment]
`get_result` does that: https://enms.readthedocs.io/en/latest/automation/workflows.html#using-the-result-of-previous-services
the content of a netmiko configuration service is a substitution string field, so it supports substitution: https://enms.readthedocs.io/en/latest/automation/services.html?highlight=substitution#substitution-fields

so you can do sth like `{{get_result(...)}}` and the value will be replaced at runtime
