### ISSUE TITLE
Git Repo Setup Failure

### ISSUE THREAD

**Issue by hikarukujo** [eNMS-automation/eNMS#318]
We setup a github repo for our device configs and pointed it at the network_data folder. When logged in as the service account, I can push/pull/clone no problem and it just works using SSH key. But when I click the button to fetch git configurations, I get the following error in my logs:

```
Mar 29 21:06:11 cersrenms01 gunicorn[9274]: [2021-03-29 21:06:11 +0000] [9274] [DEBUG] POST /get_git_content
Mar 29 21:06:11 cersrenms01 gunicorn[9274]: 2021-03-29 21:06:11,451 DEBUG    Popen(['/usr/bin/git', 'pull', '-v', 'origin'], cwd=/var/www/eNMS/network_data, universal_newlines=True, shell=None, istream=None)
Mar 29 21:06:11 cersrenms01 gunicorn[9274]: 2021-03-29 21:06:11,461 DEBUG    AutoInterrupt wait stderr: b'fatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.'
Mar 29 21:06:11 cersrenms01 gunicorn[9274]: 2021-03-29 21:06:11,461 ERROR    Git pull failed (Cmd('/usr/bin/git') failed due to: exit code(1)
Mar 29 21:06:11 cersrenms01 gunicorn[9274]:   cmdline: /usr/bin/git pull -v origin
Mar 29 21:06:11 cersrenms01 gunicorn[9274]:   stderr: 'fatal: Could not read from remote repository.
Mar 29 21:06:11 cersrenms01 gunicorn[9274]: Please make sure you have the correct access rights
Mar 29 21:06:11 cersrenms01 gunicorn[9274]: and the repository exists.')
```

Did I miss something? Thanks!

**Comment by afourmy** [comment]
Have you tried doing the same command gitpython is doing (`git pull -v origin` according to your logs) from the `network_data` folder with the exact same user you're using to run eNMS ?

**Comment by hikarukujo** [comment]
Yes, gunicorn is running as root and the permissions are all in there as root. If I sudo -sHu root and run the command, it completes successfully:

```
root@host:/var/www/eNMS/network_data# git pull -v origin
From github.com:Call-One/deviceconfigs
 = [up to date]      prod       -> origin/prod
Already up to date.
```

**Comment by afourmy** [comment]
I don't know what the issue is, but it is related to your environment since it is working for me and others...
try to run a python script that does what gitpython does i.e calling subprocess.Popen: `Popen(['/usr/bin/git', 'pull', '-v', 'origin'], cwd=/var/www/eNMS/network_data, universal_newlines=True, shell=None, istream=None)`

or try to run a python script that uses gitpython directly to pull a git repo, just like eNMS does => https://github.com/eNMS-automation/eNMS/blob/master/eNMS/controller/base.py#L173
