### ISSUE TITLE
Credential Object not functioning in 4.0.0

### ISSUE THREAD

**Issue by jsmith7735** [eNMS-automation/eNMS#319]
I am having the same issue as #314. I created a credential "test_credential" and selected the Devices_Only group. I made sure to select that Pool in the "New Service Test" workflow. I receive the below logs when trying to execute a play that requires those credentials. I attempted to remove all devices, workflows, and credentials. I thought maybe there is a specific order to creating these elements that may solve the issue. When using a fresh install with the example data, the credential store appears to function correctly. The recent change made were adding a MySQL database and adding Vault. Is there something in the example data that I need to create manually? Are there any additional logs that can be enabled to point me in the right direction?

2021-03-31 00:11:35,091 INFO     CREATION: credential 'test_credentials'
2021-03-31 00:11:51,821 INFO     UPDATE: workflow 'New Service Test': (status: 'Idle' => 'Running')
2021-03-31 00:11:52,823 INFO     USER admin - SERVICE Pull Data - DEVICE test_device - OPENING Netmiko connection
2021-03-31 00:11:53,664 INFO     UPDATE: workflow 'New Service Test': (status: 'Running' => 'Idle')

**Comment by afourmy** [comment]
Even if there is no matching credentials you should get a log that says: `2021-03-31 04:53:12.844159 - error - USER admin - SERVICE XXX - DEVICE YYY - No matching credentials found for DEVICE 'YYY' ?

Don't you have some kind of error in the workflow logs, or in the service result ?

In the credential object, did you set the "Users" property to a pool that contains the admin user that you're using here ?

**Comment by jsmith7735** [comment]
Thanks so much. The "All objects" pool did not match any users. Maybe I hosed something up? I was able to create an "All Users" pool and match the username based on the regex of ".*". I associated the newly created pool with the correct credentials object. Thanks again.
