### ISSUE TITLE
[RFE] Radius authentication

### ISSUE THREAD

**Issue by walidshaari** [eNMS-automation/eNMS#32]
it would be nice if it can do Radius authentication too.

**Comment by paultech** [comment]
Generic abstract interface works for me here too. Making Radius/LDAP/TACAS+/SSO easier to implement.

**Comment by bibin0dilli** [comment]
@walidshaari  did you get this working ,if yes how did this work for you.

**Comment by afourmy** [comment]
in the latest version, a mechanism was implemented to add new custom authentication methods in the UI, and let the user develop the associated authentication mechanism in the back-end. RADIUS won't be officially supported by eNMS but it can be added like that
