### ISSUE TITLE
Task Scheduler not functioning

### ISSUE THREAD

**Issue by jsmith7735** [eNMS-automation/eNMS#320]
I configured the scheduler based on the instructions. It appears to be waiting for jobs to be scheduled. Every task in the database states that the scheduler cannot be reached. Am missing something obvious here?

```
021-04-01 06:01:36,589 INFO     Scheduler started
2021-04-01 06:01:36,590 DEBUG    Looking for jobs to run
INFO:     Started server process [12946]
2021-04-01 06:01:36,594 INFO     Started server process [12946]
INFO:     Waiting for application startup.
2021-04-01 06:01:36,595 INFO     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
2021-04-01 06:01:36,595 INFO     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
2021-04-01 06:01:36,596 INFO     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2021-04-01 06:01:36,597 INFO     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2021-04-01 06:01:36,598 DEBUG    No jobs; waiting until a job is added
```

![image](https://user-images.githubusercontent.com/24982476/113252914-17f4e680-928a-11eb-8db8-b5c6f74586be.png)

**Comment by afourmy** [comment]
is the `SCHEDULER_ADDR` environment variable configured ?
these files show how to deploy / run the app:
https://github.com/eNMS-automation/eNMS/blob/master/build/scripts/run.sh
https://github.com/eNMS-automation/eNMS/blob/master/build/scripts/deploy.sh

**Comment by jsmith7735** [comment]
I added the environment variable. Things appear to be moving in the right direction. Now I receive the error listed below.

![image](https://user-images.githubusercontent.com/24982476/113500217-c8a8f300-94e1-11eb-9b88-75de03a248f3.png)


```
Apr 04 05:47:15 cersrenms01 uvicorn[846]: 2021-04-04 05:47:15,739 ERROR    Exception in ASGI application
Apr 04 05:47:15 cersrenms01 uvicorn[846]: Traceback (most recent call last):
Apr 04 05:47:15 cersrenms01 uvicorn[846]:   File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
Apr 04 05:47:15 cersrenms01 uvicorn[846]:     result = await app(self.scope, self.receive, self.send
Apr 04 05:47:15 cersrenms01 uvicorn[846]:   File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
Apr 04 05:47:15 cersrenms01 uvicorn[846]:     return await self.app(scope, receive, send)
Apr 04 05:47:15 cersrenms01 uvicorn[846]:   File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/asgi2.py", line 6, in __call__
Apr 04 05:47:15 cersrenms01 uvicorn[846]:     instance = self.app(scope)
Apr 04 05:47:15 cersrenms01 uvicorn[846]: TypeError: __call__() missing 1 required positional argument: 'start_response'
Apr 04 05:47:15 cersrenms01 uvicorn[846]: INFO:     127.0.0.1:48746 - "GET /next_runtime/4 HTTP/1.1" 500 Internal Server Error
```

**Comment by afourmy** [comment]
@jsmith7735 the documentation is not up-to-date, it should be deployed with gunicorn, not uvicorn.
see the files I linked above for up to date info on how to run / deploy the app, specifically:
https://github.com/eNMS-automation/eNMS/blob/master/build/scripts/run.sh#L21-L28

**Comment by jsmith7735** [comment]
I updated the run script with the command below. Things appear to be working well now.

`gunicorn --config gunicorn.py scheduler:scheduler`

![image](https://user-images.githubusercontent.com/24982476/113500951-99958000-94e7-11eb-82ba-39205362d403.png)
