### ISSUE TITLE
eNMS TACACS Error (str, bytes or bytearray expected, not NoneType)

### ISSUE THREAD

**Issue by jsmith7735** [eNMS-automation/eNMS#322]
I am having an issue getting the TACACS feature to work on eNMS. I performed a fresh install in AWS to test this feature. I am receiving the same error message as my production install. I installed the optional packages using` /var/www/html/build/requirements/requirements_optional.txt`.

2021-04-05 22:26:33,137 WARNING  Authentication error for user 'my_user' (str, bytes or bytearray expected, not NoneType)

Am I missing something obvious that may not be in the documentation?

**Comment by afourmy** [comment]
I suppose tacacs env variables `TACACS_ADDR` and `TACACS_PASSWORD` are not set, see `run.sh` file

**Comment by jsmith7735** [comment]
Thank you this resolved the issue. What is the best method to provide authorization via TACACS? Can we have some TACACS users as read-only and others as admins?
