### ISSUE TITLE
eNMS Web GUI fails to save settings 

### ISSUE THREAD

**Issue by nkane2898** [eNMS-automation/eNMS#323]
When I hit Confirm on the Settings window I see a Error 500 - Internal Server Error.

I see the following output at the same time.

2021-04-06 10:27:44,625 ERROR    Traceback (most recent call last):
  File "/home/nkane/eNMS/eNMS/server.py", line 81, in decorated_function
    return function(*args, **kwargs)
  File "/home/nkane/eNMS/eNMS/server.py", line 325, in route
    return jsonify(getattr(app, endpoint)(*args, **kwargs))
  File "/home/nkane/eNMS/eNMS/controller/administration.py", line 271, in save_settings
    if kwargs["save"]:
KeyError: 'save'

**Comment by jsmith7735** [comment]
> 
> 
> When I hit Confirm on the Settings window I see a Error 500 - Internal Server Error.
 I am experiencing the same issue.

> I see the following output at the same time.
> 
> 2021-04-06 10:27:44,625 ERROR Traceback (most recent call last):
> File "/home/nkane/eNMS/eNMS/server.py", line 81, in decorated_function
> return function(*args, **kwargs)
> File "/home/nkane/eNMS/eNMS/server.py", line 325, in route
> return jsonify(getattr(app, endpoint)(*args, **kwargs))
> File "/home/nkane/eNMS/eNMS/controller/administration.py", line 271, in save_settings
> if kwargs["save"]:
> KeyError: 'save'

**Comment by afourmy** [comment]
should be fixed in master branch
