### ISSUE TITLE
eNMS WebSSH Failure

### ISSUE THREAD

**Issue by jsmith7735** [eNMS-automation/eNMS#328]
My login attempts fail when trying to SSH to the device via the WebSSH feature within eNMS. I have tried both the browser and the Desktop connection options. When accessing the browser I receive a black screen. Hitting any key does not produce any output within the browser. When using the Desktop client I get a login prompt but all passwords attempted fail. Am I missing something obvious?

Steps to reproduce the Web Session problem.
1. Use pip install -r requirements.txt and requirements_optional.txt
2. Install sshpass and tmux
3. Create the gotty file under files/apps/
4. Find a device in the database and click on the "Connection" icon
5. On the Connection window use the IP address field, automatically authenticate, and the correct credentials
![image](https://user-images.githubusercontent.com/24982476/114479486-41850a80-9bc6-11eb-86e3-4553cb4162f4.png)
6. Click on the "Web Session" button to connect to the device via the browser.
![image](https://user-images.githubusercontent.com/24982476/114479522-55307100-9bc6-11eb-85c3-4820075c17ad.png)
7. Attempt to send commands to the device.

Steps to reproduce the Desktop authentication failure
1. Use pip install -r requirements.txt and requirements_optional.txt
2. Install sshpass and tmux
3. Create the gotty file under files/apps/
4. Find a device in the database and click on the "Connection" icon
5. On the Connection window use the IP address field, automatically authenticate, and the correct credentials
![image](https://user-images.githubusercontent.com/24982476/114479486-41850a80-9bc6-11eb-86e3-4553cb4162f4.png)
6. Click on the "Desktop Session" button to connect to the device via the browser.
7. Attempt to authenticate to the device.
```
Using username "ssh://1ae73e31-1a3f-40de-a8b9-acf1bd772a12".
Server refused our key
ssh://1ae73e31-1a3f-40de-a8b9-acf1bd772a12@enms.myserver.com's password:
Access denied
ssh://1ae73e31-1a3f-40de-a8b9-acf1bd772a12@enms.myserver.com's password:
```

**Comment by Pela2silveira** [comment]
Hello, I ran with the same issue, I solved this way:

First uninstall all flask-socketio and python-socketio packages:
<code>
pip uninstall flask-socketio
pip uninstall python-socketio
pip uninstall python-engineio
</code>
the install flask-socketio this way:
<code>
pip install "flask-socketio<5"
</code>
notice it must be pip for python3

**Comment by jsmith7735** [comment]
@Pela2silveira 

Thank you for the support. This helped me solved my problem. I actually ran into SSH key issues between the devices and the enms server. I was able to resolve that by updating the /etc/ssh/ssh_config file to add several ciphers like 3des-cbc.
