### ISSUE TITLE
Updating properties.json break eNMS UI

### ISSUE THREAD

**Issue by jsmith7735** [eNMS-automation/eNMS#329]
I would like to add a few custom fields to the eNMS device table but I am running into several issues. When I update the `custom[device]` dictionary in the properties.json file, the UI does not display any devices. Please see the code I added below.

```
{
  "custom": {
    "device": {
      "property1": {
        "pretty_name": "Property 1",
        "type": "string",
        "default": "10.145.14.1",
        "is_address": true
      },
      "serial": {
        "pretty_name": "Serial Number",
        "default": "Serial Number",
        "type": "string"
      },
```
![image](https://user-images.githubusercontent.com/24982476/114622410-8b77fa00-9c73-11eb-8d3e-f7cee9ae05c1.png)

Updates to the `table[devices]` seem to work fine. I can use the dropdown list on the devices tab to display `Serial Number`

```
  "tables": {
    "device": [
      {
        "data": "name",
        "title": "Name",
        "search": "text"
      },
      {
        "data": "description",
        "title": "Description",
        "search": "text",
        "visible": false,
        "orderable": false
      },
      {
        "data": "serial",
        "title": "Serial Number",
        "search": "text",
        "visible": false,
        "orderable": false
      },
```

Are there additional updates needed to make this function correctly?

**Comment by afourmy** [comment]
The properties.json affects the database model, so it can only be modified before eNMS runs for the first time. If you update it after that, the database will be corrupted and that would lead to the empty table you're seeing in the UI. Is that what you did ?

**Comment by jsmith7735** [comment]
Yes, this is precisely what I did. If you are unfamiliar with the app or the features, it is hard to know what you want or need. Is there a script that can be run to update the database after installation? If not, can I backup and nuke everything and restore or should I start over?

**Comment by afourmy** [comment]
> Is there a script that can be run to update the database after installation?

There are libraries to do that, but it's not part of eNMS, just standard SQL migration 

> If not, can I backup and nuke everything and restore or should I start over?

The migration mechanism available in eNMS in the admin panel can be used to backup and restore everything, but once you've corrupted the database it's too late to use it. You can still backup the content from your database with SQL
