### ISSUE TITLE
Dashboard Links Feature Request

### ISSUE THREAD

**Issue by jsmith7735** [eNMS-automation/eNMS#331]
It would be nice if the Dashboards allowed you to click the data element and get redirected to a search page of the model. As an example, if I click on Cisco under devices and vendor, I should be redirected to a search page with all devices that have Cisco set as the vendor.

**Comment by afourmy** [comment]
This is done in the new version. However, it is not a redirection to a new page; instead a panel pops up with the search table already filtered to the dashboard property.
