### ISSUE TITLE
Assigning Groups via TACACS+

### ISSUE THREAD

**Issue by jsmith7735** [eNMS-automation/eNMS#334]
Currently, when users log in to the system they are automatically created as admin users. The "Is Admin" checkbox is checked. Can this be changed via TACACS authorization?

If so, is there an example of how to return the correct value for authorization?

**Comment by afourmy** [comment]
the authentication is done in the custom file because it is meant to be customized: https://github.com/eNMS-automation/eNMS/blob/master/eNMS/controller/custom.py#L35
groups can be assigned here, and `is_admin` switched to `False`
