### ISSUE TITLE
Git Repository Syntax

### ISSUE THREAD

**Issue by dmnoit** [eNMS-automation/eNMS#343]
Hi

Is the git_repository string using the default git SSH syntax? I have a non-standard SSH port on my gitlab instance, so I'm trying it like this: `ssh://git@gitlab.INTERNALFQDN:25/corp-it/network/network-config-backups.git`. I've added the SSH keys etc.

Additionally, the documentation for the configuration backups is kind of... sparse? It seems to suggest if you create a service using the built in Netmiko Data Backup then it automatically pushes to git. I've created a service that way and it pulls the configuration (can see it in the Configuration tab)  but then nothing happens after that. Am I supposed to create another service that does the git push? I can't see an error log relating to an attempt to do the git push.

**Comment by afourmy** [comment]
> Is the git_repository string using the default git SSH syntax?

it's using whatever you set it to

> Am I supposed to create another service that does the git push?

yes, cf operational data backup workflow

**Comment by dmnoit** [comment]
Ah, I didn't see that workflow. I basically made a similar thing by creating the two services manually and running them one after the other. But, the git repository seemed to do basically nothing for me? The git service I created wouldn't work until I manually did a git init (plus a bunch of other commands to fix errors) on the network_data folder.
