### ISSUE TITLE
Scheduler always unreachable

### ISSUE THREAD

**Issue by dmnoit** [eNMS-automation/eNMS#344]
I'm binding the scheduler to 127.0.0.1:8000 (or any port) and also do `export SCHEDULER_ADDR="http://127.0.0.1:8000` but the scheduler is always unreachable. It seems like it's running fine:

`[2021-06-23 16:27:52 +0100] [45417] [INFO] Starting gunicorn 20.0.4`
`[2021-06-23 16:27:52 +0100] [45417] [DEBUG] Arbiter booted`
`[2021-06-23 16:27:52 +0100] [45417] [INFO] Listening at: http://127.0.0.1:8000 (45417)`
`[2021-06-23 16:27:52 +0100] [45417] [INFO] Using worker: sync`
`[2021-06-23 16:27:52 +0100] [45419] [INFO] Booting worker with pid: 45419`
`[2021-06-23 16:27:52 +0100] [45417] [DEBUG] 1 workers`

`2021-06-23 16:27:53,003 INFO     Scheduler started`
`2021-06-23 16:27:53,005 DEBUG    Looking for jobs to run`
`2021-06-23 16:27:53,013 DEBUG    No jobs; waiting until a job is added`

I have the ENMS ADDR,USER and PASSWORD variables set also, so it should be able to communicate back. 

I run eNMS with: `gunicorn --config /opt/eNMS/gunicorn.py --bind 127.0.0.1:5000 app:app`
and scheduler with: `gunicorn --config /opt/eNMS/scheduler/gunicorn.py --bind 127.0.0.1:8000 scheduler:scheduler`

a `curl` from the local server returns something, also:
`curl 127.0.0.1:8000`
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">`
`<title>404 Not Found</title>`
`<h1>Not Found</h1>`
`<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.`
`</p>`
What else can I check?

**Comment by afourmy** [comment]
check eNMS logs for query address, + `SCHEDULER_ADDR` env var

**Comment by dmnoit** [comment]
What logs should I be looking out for? I don't see anything relating to the scheduler, even when editing an existing Task or creating a new one. I updated the frequency of a scheduled task and this is the only log output:
`2021-06-24 11:40:12,203 INFO     UPDATE: task 'Test': (frequency: '20' => '10')`
All the logs are set to debug, and changing from Production to Debug mode in the app settings doesn't seem to make a difference.
The environment variable is definitely set:
`enms@enms:~$ echo $SCHEDULER_ADDR`
`http://127.0.0.1:8000`

**Comment by dmnoit** [comment]
Alright, I figured it out. I run gunicorn using supervisor. Apparently if you run gunicorn as a service (https://stackoverflow.com/questions/17055951/how-to-set-environment-variables-in-supervisor-service/26732916), your environment variables don't work. I had to add the envvars to the supervisor .conf file instead.

It hasn't solved my LDAP problems, however:

```
File "/opt/eNMS/eNMS/server.py", line 204, in login
    user = app.authenticate_user(**kwargs)
  File "/opt/eNMS/eNMS/controller/administration.py", line 42, in authenticate_user
    response = getattr(self, f"{method}_authentication")(user, name, password)
  File "/opt/eNMS/eNMS/controller/custom.py", line 24, in ldap_authentication
    self.ldap_server = server(getenv("LDAP_ADDR"))
NameError: name 'Server' is not defined
)
```

I tried manually defining `Server` to see if it was a problem with envvars again: 

```  
File "/opt/eNMS/eNMS/server.py", line 204, in login
    user = app.authenticate_user(**kwargs)
  File "/opt/eNMS/eNMS/controller/administration.py", line 42, in authenticate_user
    response = getattr(self, f"{method}_authentication")(user, name, password)
  File "/opt/eNMS/eNMS/controller/custom.py", line 24, in ldap_authentication
    self.ldap_server = Server(getenv("LDAP_ADDR"))
  File "/home/enms/.local/lib/python3.8/site-packages/ldap3/core/server.py", line 87, in __init__
    host = host.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
)
```

**Comment by afourmy** [comment]
looks like the ldap3 library (from the optional requirements file) is not installed ?

**Comment by dmnoit** [comment]
> looks like the ldap3 library (from the optional requirements file) is not installed ?

It's installed. I can import ldap3 from the interpreter and connect to my AD instance using a bind account. I think I've got to the point where I don't have script errors, I just get a failed auth in the logs with no other information... I think that's because my AD instance doesn't allow anonymous searching, so the base config that's in custom.py probably won't ever work and I'm too much of a python nooblet to be able to fix it myself. Also, I might be wrong because again, python nooblet, but I can't see the LDAP settings you can set in the app settings/settings.json being imported or used anywhere for LDAP auth?  

I ended up implementing RADIUS auth into the custom.py instead. Not my preferred way of doing it but it goes back to my AD instance (with an extra step) in my environment and seems to work well enough.

**Comment by afourmy** [comment]
the ldap settings are just for enabling / disabling ldap auth and setting the menu entry in the UI.

**Comment by afourmy** [comment]
the doc is not up-to-date, now you need to customize the code yourself in custom.py based on your ldap setup

**Comment by Jacobog3** [comment]
Can you please share how where you able to enable the scheduler, im having the same issue with supervisor
