### ISSUE TITLE
unable to import slack client

### ISSUE THREAD

**Issue by Pela2silveira** [eNMS-automation/eNMS#346]
I found that in 
-eNMS/models/automation.py
-eNMS/services/notification/slack_notification.py

it try to import slackclient, but does not work. 

apparently is this way [()](https://pypi.org/project/slackclient/)

from slack import WebClient

client = WebClient(token=os.environ['SLACK_API_TOKEN'])

**Comment by afourmy** [comment]
did you install slack from https://github.com/eNMS-automation/eNMS/blob/master/build/requirements/requirements_optional.txt#L7 where the version is set to < 2 ?
If you have the latest version I don't think it works.

**Comment by Pela2silveira** [comment]
I get this message: 
eNMS/services/notification/slack_notification.py:9: UserWarning: Couldn't import slackclient module (No module named 'slack')
  warn(f"Couldn't import slackclient module ({exc})")
using
slackclient            1.3.0

this is the list of installed packages:
Package                Version
---------------------- --------------------
aiofiles               0.7.0
aiohttp                3.7.4.post0
aiohttp-swagger        1.0.15
aniso8601              9.0.1
ansible                2.9.6
apache-libcloud        2.8.0
APScheduler            3.7.0
argcomplete            1.8.1
argon2-cffi            20.1.0
async-lru              1.0.2
async-timeout          3.0.1
attrs                  19.3.0
Automat                0.8.0
bcrypt                 3.2.0
bidict                 0.21.2
blinker                1.4
cached-property        1.5.1
certifi                2019.11.28
cffi                   1.14.5
chardet                3.0.4
ciscoconfparse         1.5.30
Click                  7.0
cloud-init             20.3
colorama               0.4.3
command-not-found      0.3
configobj              5.0.6
constantly             15.1.0
cryptography           2.8
dbus-python            1.2.16
dicttoxml              1.7.4
dill                   0.3.4
distro                 1.4.0
distro-info            0.23ubuntu1
dnspython              1.16.0
docker                 4.1.0
docker-compose         1.25.0
dockerpty              0.4.1
docopt                 0.6.2
entrypoints            0.3
Flask                  1.1.4
Flask-HTTPAuth         4.4.0
Flask-Login            0.5.0
Flask-RESTful          0.3.9
Flask-SocketIO         4.3.2
Flask-WTF              0.15.1
future                 0.18.2
gitdb                  4.0.7
GitPython              3.1.18
greenlet               1.1.0
gunicorn               20.1.0
httplib2               0.14.0
hvac                   0.10.14
hyperlink              19.0.0
idna                   2.8
importlib-metadata     1.5.0
incremental            16.10.1
itsdangerous           1.1.0
Jinja2                 2.11.2
jmespath               0.9.4
jsonpatch              1.22
jsonpointer            2.0
jsonschema             3.2.0
junit-xml              1.9
junos-eznc             2.6.1
keyring                18.0.1
language-selector      0.1
launchpadlib           1.10.13
lazr.restfulclient     0.14.2
lazr.uri               1.0.3
ldap3                  2.9
lockfile               0.12.2
lxml                   4.6.3
MarkupSafe             1.1.1
more-itertools         4.2.0
multidict              5.1.0
napalm                 3.3.1
ncclient               0.6.12
netaddr                0.7.19
netifaces              0.10.4
netmiko                3.4.0
ntc-templates          2.1.0
ntlm-auth              1.1.0
oauthlib               3.1.0
paramiko               2.7.2
passlib                1.7.4
pathlib                1.0.1
pathspec               0.8.1
pexpect                4.6.0
pip                    20.0.2
psutil                 5.8.0
psycopg2               2.9.1
pyasn1                 0.4.8
pyasn1-modules         0.2.1
pyats                  21.6
pyats.aereport         21.6
pyats.aetest           21.6
pyats.async            21.6
pyats.connections      21.6
pyats.datastructures   21.6
pyats.easypy           21.6
pyats.kleenex          21.6
pyats.log              21.6
pyats.reporter         21.6
pyats.results          21.6
pyats.tcl              21.6
pyats.topology         21.6
pyats.utils            21.6
pycparser              2.20
pycrypto               2.6.1
pyeapi                 0.8.4
PyGObject              3.36.0
PyHamcrest             1.9.0
PyJWT                  1.7.1
pykerberos             1.1.14
pymacaroons            0.13.0
PyNaCl                 1.3.0
pynetbox               6.1.2
pyOpenSSL              19.0.0
pyparsing              2.4.7
pyrsistent             0.15.5
pyserial               3.4
python-apt             2.0.0+ubuntu0.20.4.3
python-debian          0.1.36ubuntu1
python-engineio        3.14.2
python-socketio        4.6.1
pytz                   2021.1
pywinrm                0.3.0
PyYAML                 5.3.1
redis                  3.5.3
requests               2.22.0
requests-kerberos      0.12.0
requests-ntlm          1.1.0
requests-unixsocket    0.2.0
ruamel.yaml            0.17.10
ruamel.yaml.clib       0.2.4
scp                    0.13.5
scrapli                2021.1.30
SecretStorage          2.3.1
selinux                3.0
service-identity       18.1.0
setuptools             45.2.0
simplejson             3.16.0
six                    1.14.0
slackclient            1.3.0
smmap                  4.0.0
sos                    4.0
SQLAlchemy             1.4.20
ssh-import-id          5.10
systemd-python         234
tacacs-plus            2.6
tenacity               7.0.0
textfsm                1.1.2
texttable              1.6.2
transitions            0.8.8
Twisted                18.9.0
typing-extensions      3.10.0.0
tzlocal                2.1
ubuntu-advantage-tools 20.3
ufw                    0.36
unattended-upgrades    0.1
unicon                 21.6
unicon.plugins         21.6
urllib3                1.25.8
wadllib                1.3.3
websocket-client       0.53.0
Werkzeug               1.0.1
wheel                  0.34.2
WTForms                2.3.3
xlrd                   2.0.1
xlwt                   1.3.0
xmltodict              0.12.0
yamllint               1.26.1
yamlordereddictloader  0.4.0
yarl                   1.6.3
zipp                   1.0.0
zope.interface         4.7.1

**Comment by afourmy** [comment]
check out https://github.com/slackapi/python-slack-sdk/issues/668 maybe

**Comment by afourmy** [comment]
the slack notification service has been fixed, the newer slack sdk library is now used
